// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCMbBDST8mlvXgnbvO4dHzG-jvbjhvDMyo',
    appId: '1:1026080010447:web:5c6a446b970815cf4047ba',
    messagingSenderId: '1026080010447',
    projectId: 'the-tele-healthcare',
    authDomain: 'the-tele-healthcare.firebaseapp.com',
    storageBucket: 'the-tele-healthcare.appspot.com',
    measurementId: 'G-NQX0Z5SYHN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCBisKQ65SLFN6tPYLpTdPq5MKR55rhRjk',
    appId: '1:1026080010447:android:3d59729ad4a142814047ba',
    messagingSenderId: '1026080010447',
    projectId: 'the-tele-healthcare',
    storageBucket: 'the-tele-healthcare.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDLBhG57fdd239OTADS0Jz1ryHbH_JYHYg',
    appId: '1:1026080010447:ios:881050a9784c9cc94047ba',
    messagingSenderId: '1026080010447',
    projectId: 'the-tele-healthcare',
    storageBucket: 'the-tele-healthcare.appspot.com',
    iosBundleId: 'com.example.teleHealthcare',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDLBhG57fdd239OTADS0Jz1ryHbH_JYHYg',
    appId: '1:1026080010447:ios:f852d6c0f420ed944047ba',
    messagingSenderId: '1026080010447',
    projectId: 'the-tele-healthcare',
    storageBucket: 'the-tele-healthcare.appspot.com',
    iosBundleId: 'com.example.teleHealthcare.RunnerTests',
  );
}
