// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBie_JOu0ltOk6mu1KLQmqae0aGAl3MJw4',
    appId: '1:966299210670:web:4e4f7dedd120ea4ea12e3f',
    messagingSenderId: '966299210670',
    projectId: 'flutteradvanceconcepts',
    authDomain: 'flutteradvanceconcepts.firebaseapp.com',
    storageBucket: 'flutteradvanceconcepts.appspot.com',
    measurementId: 'G-B1DKP2WJPY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBW_W42auIC01qD5cVNr0Bqmfc61oeutdw',
    appId: '1:966299210670:android:159ae3fa687d5d97a12e3f',
    messagingSenderId: '966299210670',
    projectId: 'flutteradvanceconcepts',
    storageBucket: 'flutteradvanceconcepts.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDBqVKNdQIbxeX23KsPOjNp0N3DfO8SZoQ',
    appId: '1:966299210670:ios:18b16300ad04a3eba12e3f',
    messagingSenderId: '966299210670',
    projectId: 'flutteradvanceconcepts',
    storageBucket: 'flutteradvanceconcepts.appspot.com',
    iosBundleId: 'com.example.flutteradvanceconcepts',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDBqVKNdQIbxeX23KsPOjNp0N3DfO8SZoQ',
    appId: '1:966299210670:ios:b74f9faa2d13955ca12e3f',
    messagingSenderId: '966299210670',
    projectId: 'flutteradvanceconcepts',
    storageBucket: 'flutteradvanceconcepts.appspot.com',
    iosBundleId: 'com.example.flutteradvanceconcepts.RunnerTests',
  );
}
