// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBMj7KJYJ3uR8K7jEK0fqllfgJ9DFQSFA0',
    appId: '1:147944791241:web:9dbdaae56933ceb8b64118',
    messagingSenderId: '147944791241',
    projectId: 'sky-multi-store-app',
    authDomain: 'sky-multi-store-app.firebaseapp.com',
    storageBucket: 'sky-multi-store-app.appspot.com',
    measurementId: 'G-R94Y4NXL8K',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCp2JtDjHbCRkabCNvP8YmfObWRt-_Y1jE',
    appId: '1:147944791241:android:224f4d1fcd4e3bc3b64118',
    messagingSenderId: '147944791241',
    projectId: 'sky-multi-store-app',
    storageBucket: 'sky-multi-store-app.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCVQ2Jbj39Y7bAtrbuBrRJs3xlSm9nBmpk',
    appId: '1:147944791241:ios:8cca3811948855b1b64118',
    messagingSenderId: '147944791241',
    projectId: 'sky-multi-store-app',
    storageBucket: 'sky-multi-store-app.appspot.com',
    iosBundleId: 'com.example.multiStoreApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCVQ2Jbj39Y7bAtrbuBrRJs3xlSm9nBmpk',
    appId: '1:147944791241:ios:aeefe8488b7796beb64118',
    messagingSenderId: '147944791241',
    projectId: 'sky-multi-store-app',
    storageBucket: 'sky-multi-store-app.appspot.com',
    iosBundleId: 'com.example.multiStoreApp.RunnerTests',
  );
}
